#!/bin/bash

set -o errexit -o nounset -o pipefail

umask 077

cd /etc/nginx/session_ticket_keys

openssl rand -out 1.key 80
openssl rand -out 2.key 80
openssl rand -out 3.key 80
openssl rand -out 4.key 80
