#!/bin/sh

set -o errexit -o nounset

umask 077

cd /etc/nginx/session-ticket-keys

for i in 1 2 3; do
	cp -p "$((i + 1)).key" "$i.key"
done

dd ibs=1 obs=1 count='80' 2>/dev/null </dev/urandom >4.key

if [ "$#" -gt 0 ]; then
	[ "$1" = '-r' ] && nginx -s reload
fi
