#!/bin/sh

set -o errexit -o nounset

umask 077

cd /etc/nginx/session-ticket-keys

for i in 1 2 3; do
	cp -p "$((i + 1)).key" "$i.key"
done

# use /dev/random instead of urandom in case urandom hasn't been seeded
# on modern kernels it is good enough for our purposes
dd ibs=1 obs=1 count='80' 2>/dev/null </dev/random >4.key

if [ "$#" -gt 0 ]; then
	[ "$1" = '-r' ] && nginx -s reload
fi
